import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/ui/global.css';
import Navbar from '@/app/components/Navbar';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { JobsProvider } from '@/app/context/JobsContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <JobsProvider>
          <Navbar />
          <main>{children}</main>
          <ToastContainer />
        </JobsProvider>
      </body>
    </html>
  );
};

export default RootLayout;